#ifndef UPFIRE_DLL_COFF_GLOBAL_H
#define UPFIRE_DLL_COFF_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UPFIRE_DLL_COFF_LIBRARY)
#  define UPFIRE_DLL_COFFSHARED_EXPORT Q_DECL_EXPORT
#else
#  define UPFIRE_DLL_COFFSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // UPFIRE_DLL_COFF_GLOBAL_H
